working on windows release

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -80,6 +80,7 @@ jobs:
         run: |
           New-Item -ItemType Directory -Force -Path icons_backup
           Copy-Item -Path "src-tauri/icons/*" -Destination icons_backup -Recurse -Force
+          Get-ChildItem icons_backup  # Verify the backup
 
       - name: Backup icons
         if: runner.os != 'Windows'
@@ -105,11 +106,13 @@ jobs:
         if: runner.os == 'Windows'
         shell: powershell
         run: |
-          if (-not (Test-Path src-tauri/icons)) {
-              New-Item -ItemType Directory -Force -Path src-tauri/icons
-          }
+          New-Item -ItemType Directory -Force -Path src-tauri/icons
           Copy-Item -Path "icons_backup/*" -Destination src-tauri/icons -Recurse -Force
           Get-ChildItem src-tauri/icons  # Verify the icons are restored
+          if (-not (Test-Path "src-tauri/icons/icon.ico")) {
+            Write-Error "icon.ico not found after restore!"
+            exit 1
+          }
 
       - name: Restore icons
         if: runner.os != 'Windows'
